/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni202557201005;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ANGGUN Z
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    private CardLayout cardLayout;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        inisiasiPanel();
    }
    void inisiasiPanel(){
        cardLayout = (CardLayout)PanelContent.getLayout();
        PanelContent.add(new PanelDashboardNew(), "dashboard");
        PanelContent.add(new PanelJurusan(), "jurusan");
        PanelContent.add(new PanelGuru(), "guru");
        PanelContent.add(new PanelKelas(), "kelas");
        PanelContent.add(new PanelSiswa(), "siswa");
        PanelContent.add(new PanelAbout(), "about");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContent = new javax.swing.JPanel();
        panelSidebar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bDashboard = new javax.swing.JButton();
        bJurusan = new javax.swing.JButton();
        bGuru = new javax.swing.JButton();
        bKelas = new javax.swing.JButton();
        bSiswa = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(961, 604));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(961, 604));

        PanelContent.setMinimumSize(new java.awt.Dimension(802, 604));
        PanelContent.setPreferredSize(new java.awt.Dimension(802, 604));
        PanelContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(PanelContent, java.awt.BorderLayout.LINE_END);

        panelSidebar.setBackground(new java.awt.Color(114, 167, 239));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-graduation-32.png"))); // NOI18N
        jLabel2.setText("Aloomni");

        bDashboard.setBackground(new java.awt.Color(114, 167, 239));
        bDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bDashboard.setForeground(new java.awt.Color(255, 255, 255));
        bDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-dashboard-gauge-18.png"))); // NOI18N
        bDashboard.setText("Dashboard");
        bDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDashboard.setIconTextGap(10);
        bDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDashboardActionPerformed(evt);
            }
        });

        bJurusan.setBackground(new java.awt.Color(114, 167, 239));
        bJurusan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bJurusan.setForeground(new java.awt.Color(255, 255, 255));
        bJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-building-18.png"))); // NOI18N
        bJurusan.setText("Jurusan");
        bJurusan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bJurusan.setIconTextGap(10);
        bJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJurusanActionPerformed(evt);
            }
        });

        bGuru.setBackground(new java.awt.Color(114, 167, 239));
        bGuru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bGuru.setForeground(new java.awt.Color(255, 255, 255));
        bGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-classroom-19.png"))); // NOI18N
        bGuru.setText("Guru");
        bGuru.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bGuru.setIconTextGap(10);
        bGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuruActionPerformed(evt);
            }
        });

        bKelas.setBackground(new java.awt.Color(114, 167, 239));
        bKelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bKelas.setForeground(new java.awt.Color(255, 255, 255));
        bKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-class-18.png"))); // NOI18N
        bKelas.setText("Kelas");
        bKelas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bKelas.setIconTextGap(10);
        bKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKelasActionPerformed(evt);
            }
        });

        bSiswa.setBackground(new java.awt.Color(114, 167, 239));
        bSiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bSiswa.setForeground(new java.awt.Color(255, 255, 255));
        bSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-person-18.png"))); // NOI18N
        bSiswa.setText("Siswa");
        bSiswa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bSiswa.setIconTextGap(10);
        bSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSiswaActionPerformed(evt);
            }
        });

        bAbout.setBackground(new java.awt.Color(114, 167, 239));
        bAbout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bAbout.setForeground(new java.awt.Color(255, 255, 255));
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-about-18.png"))); // NOI18N
        bAbout.setText("About Us");
        bAbout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAbout.setIconTextGap(10);
        bAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAboutActionPerformed(evt);
            }
        });

        bLogout.setBackground(new java.awt.Color(114, 167, 239));
        bLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bLogout.setForeground(new java.awt.Color(255, 255, 255));
        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-logout-18.png"))); // NOI18N
        bLogout.setText("Logout");
        bLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        bLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bLogout.setIconTextGap(10);
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addComponent(bDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addComponent(bDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bJurusan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bGuru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bSiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLogout)
                .addContainerGap(283, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDashboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "dashboard");
    }//GEN-LAST:event_bDashboardActionPerformed

    private void bJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJurusanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "jurusan");
    }//GEN-LAST:event_bJurusanActionPerformed

    private void bGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuruActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "guru");
    }//GEN-LAST:event_bGuruActionPerformed

    private void bKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKelasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "kelas");
    }//GEN-LAST:event_bKelasActionPerformed

    private void bSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiswaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "siswa");
    }//GEN-LAST:event_bSiswaActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(PanelContent, "about");
    }//GEN-LAST:event_bAboutActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        int pilihan = JOptionPane.showConfirmDialog(
                null,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        switch (pilihan) {
            case JOptionPane.YES_OPTION:
                dispose();
                new frameLogin().setVisible(true);
                break;
            case JOptionPane.NO_OPTION:
                break;   
            default:
                break;
        }
    }//GEN-LAST:event_bLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            
            /*
            UIManager.put("Button.arc", 15);
            UIManager.put("Button.borderWidth", 0);
            UIManager.put("TextComponent.arc", 15);
            UIManager.put("Component.BorderWidth", 0);
            UIManager.put("Component.focusWidth", 0);
            UIManager.put("Component.innerFocusWidth", 0);*/
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContent;
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bDashboard;
    private javax.swing.JButton bGuru;
    private javax.swing.JButton bJurusan;
    private javax.swing.JButton bKelas;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bSiswa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
