/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201005;

/**
 *
 * @author ANGGUN Z
 */
public class PanelDashboardNew extends javax.swing.JPanel {

    /**
     * Creates new form PanelJurusanNew
     */
    public PanelDashboardNew() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jumlahJurusan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jumlahGuru = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jumlahSiswa = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jumlahKelas = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(802, 604));
        setPreferredSize(new java.awt.Dimension(802, 604));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 7));
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jumlahJurusan.setMinimumSize(new java.awt.Dimension(190, 150));
        jumlahJurusan.setPreferredSize(new java.awt.Dimension(190, 150));
        jumlahJurusan.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(762, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(762, 150));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel9.setBackground(new java.awt.Color(114, 167, 239));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Jumlah Jurusan");
        jLabel9.setMaximumSize(new java.awt.Dimension(37, 30));
        jLabel9.setMinimumSize(new java.awt.Dimension(37, 30));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel3.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("JJ");
        jLabel1.setMaximumSize(new java.awt.Dimension(119, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(119, 100));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        jumlahJurusan.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jumlahJurusan);

        jumlahGuru.setMinimumSize(new java.awt.Dimension(190, 150));
        jumlahGuru.setPreferredSize(new java.awt.Dimension(190, 150));
        jumlahGuru.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(762, 150));
        jPanel5.setPreferredSize(new java.awt.Dimension(762, 150));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(new java.awt.Color(114, 167, 239));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Jumlah Guru");
        jLabel10.setMaximumSize(new java.awt.Dimension(37, 30));
        jLabel10.setMinimumSize(new java.awt.Dimension(37, 30));
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel5.add(jLabel10, java.awt.BorderLayout.PAGE_START);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("JG");
        jLabel2.setMaximumSize(new java.awt.Dimension(119, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(119, 100));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel5.add(jLabel2, java.awt.BorderLayout.CENTER);

        jumlahGuru.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jumlahGuru);

        jumlahSiswa.setMinimumSize(new java.awt.Dimension(190, 150));
        jumlahSiswa.setPreferredSize(new java.awt.Dimension(190, 150));
        jumlahSiswa.setLayout(new java.awt.BorderLayout());

        jPanel7.setMinimumSize(new java.awt.Dimension(762, 150));
        jPanel7.setPreferredSize(new java.awt.Dimension(762, 150));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(114, 167, 239));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Jumlah Siswa");
        jLabel11.setMaximumSize(new java.awt.Dimension(37, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(37, 30));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel7.add(jLabel11, java.awt.BorderLayout.PAGE_START);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("JS");
        jLabel3.setMaximumSize(new java.awt.Dimension(119, 100));
        jLabel3.setMinimumSize(new java.awt.Dimension(119, 100));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel7.add(jLabel3, java.awt.BorderLayout.CENTER);

        jumlahSiswa.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jumlahSiswa);

        jumlahKelas.setMinimumSize(new java.awt.Dimension(190, 150));
        jumlahKelas.setPreferredSize(new java.awt.Dimension(190, 150));
        jumlahKelas.setLayout(new java.awt.BorderLayout());

        jPanel9.setMinimumSize(new java.awt.Dimension(762, 150));
        jPanel9.setPreferredSize(new java.awt.Dimension(762, 150));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel12.setBackground(new java.awt.Color(114, 167, 239));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Jumlah Kelas");
        jLabel12.setMaximumSize(new java.awt.Dimension(37, 30));
        jLabel12.setMinimumSize(new java.awt.Dimension(37, 30));
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel9.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("JK");
        jLabel4.setMaximumSize(new java.awt.Dimension(119, 100));
        jLabel4.setMinimumSize(new java.awt.Dimension(119, 100));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel9.add(jLabel4, java.awt.BorderLayout.CENTER);

        jumlahKelas.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jumlahKelas);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jumlahGuru;
    private javax.swing.JPanel jumlahJurusan;
    private javax.swing.JPanel jumlahKelas;
    private javax.swing.JPanel jumlahSiswa;
    // End of variables declaration//GEN-END:variables
}
