/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201005;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ANGGUN Z
 */
public class PanelGuru extends javax.swing.JPanel {

    /**
     * Creates new form PanelGuru
     */
    public PanelGuru() {
        initComponents();
        // Mengosongkan form input dan mengatur ulang komponen input
        reset();
        
        // Memuat data dari database ke dalam tabel guru pada GUI
        load_tabel_guru();
    }
    
    // Method untuk mereset (mngosongkan) form input
    void reset(){
        // Kosongkan field NIP
        tNIP.setText(null);
        
        // Aktifkan kembali agar NIP bisa diedit
        tNIP.setEditable(true);
        
        // Kosongkan field nama guru
        tNamaGuru.setText(null);
        
        // Reset pilihan jenis kelamin (combo box)
        cJenisKelamin.setSelectedItem(null);
        
        // Kosongkan field alamat
        tAlamat.setText(null);
    }
    
    // Method untuk memuat data dari tabel'guru' ke dalam tabel GUI (tblGuru)
    void load_tabel_guru (){
        // Membuat model tabel baru 
        DefaultTableModel model = new DefaultTableModel();
        
        // MEnambahkan nama kolom ke dalam model tabel
        model.addColumn("NIP");
        model.addColumn("Nama Guru");
        model.addColumn("L/P");
        model.addColumn("Alamat");
        
        // SQL untuk mengambil semua data dari tabel guru
        String sql = "SELECT * FROM guru";
        
        try {
            // Membuka koneksi ke database
            Connection conn = koneksi.konek();

            // Membuat statement SQL
            Statement st = conn.createStatement();

            // Menjalankan query dan menyimpan hasilnya 
            ResultSet rs = st.executeQuery(sql);

            // Iterasi untuk setiap baris hasil query 
            while (rs.next()) {
                // Mengambil nilai dari masing-masing kolom
                String NIP = rs.getString("nip");
                String namaGuru = rs.getString("nama_guru");
                String jenisKelamin = rs.getString("gender");
                String alamat = rs.getString("alamat");

                // Menyusun data ke dalam array objek 
                Object[] baris = {NIP, namaGuru, jenisKelamin, alamat};

                // Menambahkan data ke model tabel
                model.addRow(baris);
            }
        } catch (SQLException sQLException) {
            // Menampilkan pesan error jika terjadi kegagalan
            JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
        }
       
        // Menampilkan data model ke dalam tabel GUI
        tblGuru.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tNIP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tNamaGuru = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cJenisKelamin = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuru = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setMinimumSize(new java.awt.Dimension(802, 604));
        setPreferredSize(new java.awt.Dimension(802, 604));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(114, 167, 239));
        jPanel1.setPreferredSize(new java.awt.Dimension(483, 30));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Guru");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel1.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-close-20 (1).png"))); // NOI18N
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(255, 296));
        jPanel5.setPreferredSize(new java.awt.Dimension(255, 296));

        jLabel1.setText("NIP");

        tNIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNIPActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        jLabel3.setText("Jenis Kelamin");

        cJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        cJenisKelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cJenisKelaminActionPerformed(evt);
            }
        });

        jLabel4.setText("Alamat");

        tAlamat.setColumns(20);
        tAlamat.setRows(5);
        jScrollPane2.setViewportView(tAlamat);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tNIP)
                    .addComponent(tNamaGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(cJenisKelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNIP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tNamaGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btnHapus.setBackground(new java.awt.Color(255, 0, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-trash-18.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(114, 167, 239));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-resetwhite-18.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(102, 204, 0));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-plus-18.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 153, 0));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201005/img/Aloomni/icons8-pen-squared-18.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 20));
        jPanel6.setLayout(new java.awt.CardLayout());

        tblGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGuru);

        jPanel6.add(jScrollPane1, "card2");

        jPanel2.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void cJenisKelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cJenisKelaminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cJenisKelaminActionPerformed

    private void tNIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNIPActionPerformed

    private void tblGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGuruMouseClicked
        // TODO add your handling code here:
        
        // Mengambil indeks baris yang diklik oleh pengguna di tabel tblGuru
        int barisYangDipilih = tblGuru.rowAtPoint(evt.getPoint());
        
        // Mengambil nilai NIP dari kolom pertama (indeks 0) pada baris yang dipilih
        String NIP = tblGuru.getValueAt(barisYangDipilih, 0).toString();
        
        // Mengambil nilai nama guru dari kolom kedua (indeks 1) pada baris yang dipilih 
        String namaGuru = tblGuru.getValueAt(barisYangDipilih, 1).toString();
        
        // Mengambil nilai jenis kelamin dari kolom ketiga (indeks 2) pada baris yang dipilih
        //String jenisKelamin = tblGuru.getValueAt(barisYangDipilih, 2).toString();
        Object JK = tblGuru.getValueAt(barisYangDipilih, 2);

        String jenisKelamin = "";
        if (JK != null) {
        jenisKelamin = JK.toString();

}
        // Mengambil nilai alamat dari kolom ke empat (indeks3) pada baris yang dipilih
        // String alamat = tblGuru.getValueAt(barisYangDipilih, 3).toString();
        Object dataAlamat = tblGuru.getValueAt(barisYangDipilih, 3);
                
        String alamat = "";
        if(dataAlamat != null){
            alamat = dataAlamat.toString();
        }
        // Menampilkan nilai NIP ke dalam text field tNIP
        tNIP.setText(NIP);
        
        // Menonaktifkan field NIP agar tidak bisa diedit (karena NIP bersifat unik dan tiddak boleh diubah)
        tNIP.setEditable(false);
        
        // Menampilkan nama guru ke dalam text field tNamaGuru
        tNamaGuru.setText(namaGuru);
        
        // Menampilkan alamat ke dalam text field tAlamat
        tAlamat.setText(alamat);
        
        // Mengecek isi nilai jenis kelamin dan menyesuaikan pilihan pada combo box  cJenisKelamin
        switch (jenisKelamin) {
            // Jika nilai jenis kelamin "L", set pilihan combo box ke "Laki - laki"
            case "L" :
                cJenisKelamin.setSelectedItem("Laki - laki");
                break;
            // Jika nilai jenis kelamin "P", set pilihan combo box ke "Perempuan"
            case "P" :
                cJenisKelamin.setSelectedItem("Perempuan");
                break;
            // Jika nilainya bukan "L" atau "P", kosongkan pilihan combo box
            default:
                cJenisKelamin.setSelectedItem(null);
                break;
        }
    }//GEN-LAST:event_tblGuruMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        
        // Mengambil input NIP dari text field tNIP
        String NIP = tNIP.getText();
        
        // Mengambil input nama guru text  field tNamaGuru
        String namaGuru = tNamaGuru.getText();
        
        // Mengambil item yang dipilih dari combo box jenis kelamin 
        String jenisKelamin = cJenisKelamin.getSelectedItem().toString();
        
        // Mengambil input alamat dari text field tAlamat
        String alamat  = tAlamat.getText();
        
        // Menyiapkan variabel JK (jenis kelamin dalam format singkatan "L" atau "P")
        String jK = null;
        
        // Mengubah nilai jenisKelamin dari label menjadi format singkatan yang disimpan di  database
        switch (jenisKelamin) {
            case "Laki - laki":
                jK = "L";
                break;
            case "Perempuan":
                jK = "P";
                break;
            default:
                jK = null;
                break;
        }
        
        // Menyusun perintah SQL untuk menyisipkan data guru ke dalam tabel guru
        String sql = "INSERT INTO guru(nip, nama_guru, gender, alamat) VALUES(?,?,?,?)";
        
        
        try {
            // MMembuka koneksi ke database menggunakan method konek()
            Connection conn = koneksi.konek();

            // Mempersiapkan query SQL dengan parameter (prepared statement
            PreparedStatement ps = conn.prepareStatement(sql);

            // Mengisi parameter pertama dengan NIP
            ps.setString(1, NIP);

            // Mengisi parameter kedua dengan nama guru
            ps.setString(2, namaGuru);

            // Mengisi parameter ketiga dengan jenis kelamin (L atau P)
            ps.setString(3, jK);

            // Mengisi parameter keempat dengan alamat
            ps.setString(4, alamat);

            // Menjalankan perintah INSERT untuk menyimpan data ke database 
            ps.execute();

            // Menampilkan pesan bahwa data berhasil disimpan
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        } catch (SQLException sQLException) {
            // Menampilkan pesan jika terjadi kesalahan daat menyimpan data
            JOptionPane.showMessageDialog(null, "Data gagal disimpan!");
        } 
        
        // Memuat ulang data guru di tabel tampilan
        load_tabel_guru();
        
        // Mereset semua input agar kosong kembali
        reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        
        // Mengambil nilai NIP dari text field tNIP 
        String NIP = tNIP.getText();
        
        // Mengambil nama guru dari text field tNamaGuru
        String namaGuru = tNamaGuru.getText();
        
        // Mengambil item yang dipilih dari combo  box jenis kelamin
        String jenisKelammin = cJenisKelamin.getSelectedItem().toString();
        
        // Mengambil alamat dari text field tAlamat
        String alamat = tAlamat.getText();
        
        // Menyiapkan variabel untuk menyimpan singkatan jenis kelamin ("L" atau "P")
        String jK = null;
        
        // Mengubah label jenis kelamin menjadi singkatan yanngg sesuai dengan format database
        switch (jenisKelammin) {
            case "Laki - laki":
                jK = "L";
                break;
            case "Perempuan":
                jK = "P";
                break;
            default:
                jK = null;
                break;
        }
        
        // Menyusun perintah SQL untuk memperbarui data guru berdasarkan NIP
        String sql = "UPDATE guru SET nama_guru=?, gender=?, alamat=? WHERE nip=?";
        
        try {
            // Membuka koneksi ke database
            Connection conn = koneksi.konek();

            // Mempersiapkan statement SQL dengan parameter (prepared statement)
            PreparedStatement ps = conn.prepareStatement(sql);

            // Mengisi  parameter pertama (?) dengan nama guru
            ps.setString(1, namaGuru);

            // Megisi parameter kedua (?) dengan jenis kelamin ("L"/"P")
            ps.setString(2, jK);

            // Mengisi parameter ketiga (?) dengan alamat
            ps.setString(3, alamat);

            // Megisi parameter keempat (?) dengan NIP sebagai identitas data yang akan diubah
            ps.setString(4, NIP);

            // Menjalankan perintah UPDATE
            ps.execute();

            // Menampilkan pesan bahwa data berhasil diubah
            JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
        } catch (SQLException sQLException) {
            // Menampilkan pesan jika proses update gagal
            JOptionPane.showMessageDialog(null, "Data gagal diubah!");
        } 
        
        // Membuat ulang tabel guru untuk menampilkan data terbaru
        load_tabel_guru();
        
        // Mereset/mengosongkan form input
        reset();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        
        // Mengammbil nilai NIP dari text field tNIP
        String NIP = tNIP.getText();
        
        // Meyusun perintah SQL untuk menghapus data berdasarkan NIP
        String sql = "DELETE FROM guru WHERE nip=?";
        
        try {
            // Membuka koneksi ke database
            Connection conn = koneksi.konek();

            // Menyiapkan statement SQL dengan parameter (prepared statement)
            PreparedStatement ps = conn.prepareStatement(sql);

            // Mengisi parameter pertama (?) dengan nilai NIP
            ps.setString(1, NIP);

            // Menjalankan perintah DELETE untuk menghapus data dari database
            ps.execute();

            // Menampilkan pesan jika data berhasil dihapus 
            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (SQLException sQLException) {
            // Menampilkan pesan jika terjadi kesalahan saat proses penghapusan 
            JOptionPane.showMessageDialog(null, "Data gagal dihapus!");
        } 
        
        // Memuat ulang data pada tabel guru setelah penghapusan
        load_tabel_guru();
        
        // Mereset atau  mengosongkan form input
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cJenisKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tNIP;
    private javax.swing.JTextField tNamaGuru;
    private javax.swing.JTable tblGuru;
    // End of variables declaration//GEN-END:variables
}
