/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201005;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.Connection;
import java.sql.SQLException;

/**
 *
 * @author ANGGUN Z
 */
public class PanelDashboardNew extends javax.swing.JPanel {

    /**
     * Creates new form PanelJurusanNew
     */
    public PanelDashboardNew() {
        initComponents();
        isiJumlahDataDasbor();
    }

    private void isiJumlahDataDasbor(){
        // Membuka koneksi ke database
        Connection conn = koneksi.konek();
        
        try {
            // Mengambil jumlah jurusan tabel jurusan
            String sqlJurusan = "SELECT COUNT(*) AS jumlah FROM jurusan";
            Statement psJurusan = conn.createStatement();
            ResultSet rsJurusan = psJurusan.executeQuery(sqlJurusan);
            
            // Jika hasil query ada, ambil dan tampilkan ke label jumlah jurusan
            if (rsJurusan.next()) {
                int jumlah = rsJurusan.getInt("jumlah");
                tJumlahJurusan.setText(String.valueOf(jumlah));
            }
            
            // Mengambil jumlah guru dari tabel guru
            String sqlGuru = "SELECT COUNT(*) AS jumlah FROM guru";
            Statement psGuru = conn.createStatement();
            ResultSet rsGuru = psGuru.executeQuery(sqlGuru);
            
            // Jika hasil query ada, ambil dan tampilkan ke label jumlah jurusan
            if (rsGuru.next()) {
                int jumlah = rsGuru.getInt("jumlah");
                tJumlahGuru.setText(String.valueOf(jumlah));
            }
            
            // Mengambil jumlah siswa dari tabel siswa
            String sqlSiswa = "SELECT COUNT(*) AS jumlah FROM siswa";
            Statement psSiswa = conn.createStatement();
            ResultSet rsSiswa = psSiswa.executeQuery(sqlSiswa);
            
            // Jika hasil query ada, ambil dan tampilkan ke label jumlah jurusan
            if (rsSiswa.next()) {
                int jumlah = rsSiswa.getInt("jumlah");
                tJumlahSiswa.setText(String.valueOf(jumlah));
            }
            
            // Mengambil jumlah kelas dari tabel kelas
            String sqlKelas = "SELECT COUNT(*) AS jumlah FROM kelas";
            Statement psKelas = conn.createStatement();
            ResultSet rsKelas = psKelas.executeQuery(sqlKelas);
            
            // Jika hasil query ada, ambil dan tampilkan ke label jumlah jurusan
            if (rsKelas.next()) {
                int jumlah = rsKelas.getInt("jumlah");
                tJumlahKelas.setText(String.valueOf(jumlah));
            }
        } catch (SQLException e) {
            
            // Menampilkan pesan di konsol jika terjadi error saat mengambil data 
            System.out.println("Gagal mengambil jumlah data");
        }
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jumlahJurusan = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tJumlahJurusan = new javax.swing.JLabel();
        jumlahGuru = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        tJumlahGuru = new javax.swing.JLabel();
        jumlahSiswa = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tJumlahSiswa = new javax.swing.JLabel();
        jumlahKelas = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tJumlahKelas = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setMinimumSize(new java.awt.Dimension(802, 604));
        setPreferredSize(new java.awt.Dimension(802, 604));
        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jumlahJurusan.setMinimumSize(new java.awt.Dimension(190, 150));
        jumlahJurusan.setPreferredSize(new java.awt.Dimension(190, 150));
        jumlahJurusan.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(762, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(762, 150));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel9.setBackground(new java.awt.Color(114, 167, 239));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Jumlah Jurusan");
        jLabel9.setMaximumSize(new java.awt.Dimension(37, 30));
        jLabel9.setMinimumSize(new java.awt.Dimension(37, 30));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel3.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        tJumlahJurusan.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahJurusan.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tJumlahJurusan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahJurusan.setText("JJ");
        tJumlahJurusan.setMaximumSize(new java.awt.Dimension(119, 100));
        tJumlahJurusan.setMinimumSize(new java.awt.Dimension(119, 100));
        tJumlahJurusan.setOpaque(true);
        tJumlahJurusan.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel3.add(tJumlahJurusan, java.awt.BorderLayout.CENTER);

        jumlahJurusan.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jumlahJurusan);

        jumlahGuru.setMinimumSize(new java.awt.Dimension(190, 150));
        jumlahGuru.setPreferredSize(new java.awt.Dimension(190, 150));
        jumlahGuru.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(762, 150));
        jPanel5.setPreferredSize(new java.awt.Dimension(762, 150));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel10.setBackground(new java.awt.Color(114, 167, 239));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Jumlah Guru");
        jLabel10.setMaximumSize(new java.awt.Dimension(37, 30));
        jLabel10.setMinimumSize(new java.awt.Dimension(37, 30));
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel5.add(jLabel10, java.awt.BorderLayout.PAGE_START);

        tJumlahGuru.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahGuru.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tJumlahGuru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahGuru.setText("JG");
        tJumlahGuru.setMaximumSize(new java.awt.Dimension(119, 100));
        tJumlahGuru.setMinimumSize(new java.awt.Dimension(119, 100));
        tJumlahGuru.setOpaque(true);
        tJumlahGuru.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel5.add(tJumlahGuru, java.awt.BorderLayout.CENTER);

        jumlahGuru.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jumlahGuru);

        jumlahSiswa.setMinimumSize(new java.awt.Dimension(190, 150));
        jumlahSiswa.setPreferredSize(new java.awt.Dimension(190, 150));
        jumlahSiswa.setLayout(new java.awt.BorderLayout());

        jPanel7.setMinimumSize(new java.awt.Dimension(762, 150));
        jPanel7.setPreferredSize(new java.awt.Dimension(762, 150));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(114, 167, 239));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Jumlah Siswa");
        jLabel11.setMaximumSize(new java.awt.Dimension(37, 30));
        jLabel11.setMinimumSize(new java.awt.Dimension(37, 30));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel7.add(jLabel11, java.awt.BorderLayout.PAGE_START);

        tJumlahSiswa.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahSiswa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tJumlahSiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahSiswa.setText("JS");
        tJumlahSiswa.setMaximumSize(new java.awt.Dimension(119, 100));
        tJumlahSiswa.setMinimumSize(new java.awt.Dimension(119, 100));
        tJumlahSiswa.setOpaque(true);
        tJumlahSiswa.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel7.add(tJumlahSiswa, java.awt.BorderLayout.CENTER);

        jumlahSiswa.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jumlahSiswa);

        jumlahKelas.setMinimumSize(new java.awt.Dimension(190, 150));
        jumlahKelas.setPreferredSize(new java.awt.Dimension(190, 150));
        jumlahKelas.setLayout(new java.awt.BorderLayout());

        jPanel9.setMinimumSize(new java.awt.Dimension(762, 150));
        jPanel9.setPreferredSize(new java.awt.Dimension(762, 150));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel12.setBackground(new java.awt.Color(114, 167, 239));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Jumlah Kelas");
        jLabel12.setMaximumSize(new java.awt.Dimension(37, 30));
        jLabel12.setMinimumSize(new java.awt.Dimension(37, 30));
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(37, 30));
        jPanel9.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        tJumlahKelas.setBackground(new java.awt.Color(255, 255, 255));
        tJumlahKelas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tJumlahKelas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tJumlahKelas.setText("JK");
        tJumlahKelas.setMaximumSize(new java.awt.Dimension(119, 100));
        tJumlahKelas.setMinimumSize(new java.awt.Dimension(119, 100));
        tJumlahKelas.setOpaque(true);
        tJumlahKelas.setPreferredSize(new java.awt.Dimension(119, 100));
        jPanel9.add(tJumlahKelas, java.awt.BorderLayout.CENTER);

        jumlahKelas.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jumlahKelas);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jumlahGuru;
    private javax.swing.JPanel jumlahJurusan;
    private javax.swing.JPanel jumlahKelas;
    private javax.swing.JPanel jumlahSiswa;
    private javax.swing.JLabel tJumlahGuru;
    private javax.swing.JLabel tJumlahJurusan;
    private javax.swing.JLabel tJumlahKelas;
    private javax.swing.JLabel tJumlahSiswa;
    // End of variables declaration//GEN-END:variables
}
